#!/usr/bin/env bash

alias ag='ag --path-to-ignore ~/dotfiles/.agignore'
alias cl='clear'
alias cp='cp -i'
alias cs='cursor-agent'
alias dc='docker compose'
alias dcrun='docker compose run --rm'
alias dl='cd ~/Downloads'
alias dt='cd ~/Desktop'
alias fnm='fnm2'
alias grep="GREP_COLOR='1;32' grep --color"
alias ls='lsd'
alias la='lsd -la --group-dirs first --date relative --size short'
alias lt='lsd --tree --ignore-glob node_modules --ignore-glob .git'
alias lzd='lazydocker'
alias lzg='lazygit'
alias mp='cd ~/Projects'
alias mv='mv -i'
alias nest='npx --yes @nestjs/cli'
alias npmls='npm list --location=global --depth=0'
alias npx='npx --yes'
alias oc='opencode'
alias oll='ollama'
alias pip='pip3'
alias ppp='pnpm'
alias ppx='pnpm dlx'
alias po='poetry'
alias randomport='jot -r 1 55000 55999'
alias rm='rm -i'
alias sgrep='grep -R -n -H -C 5 --exclude-dir={.git,.svn,CVS} '
alias vvv='virtualenv env && source ./env/bin/activate' # for python virtualenv
alias whisperx='whisperx --compute_type int8'
alias zshrc='nvim ~/dotfiles/zshrc'
alias nvm-upgrade='nvm install --lts --reinstall-packages-from=$(node -v)'

alias openlocal='ngrok http --region=us --hostname=ants.ngrok.io' # -region=eu -subdomain=sa -host-header=rewrite 3000'

alias redis='redis-cli'

# For golang development
alias air='$HOME/.local/bin/air'

alias luamake='$HOME/.config/lua-language-server/3rd/luamake/luamake'
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

# Control mongodb
alias startmongo='mongod --config $HOME/.local/mongodb/mongod.conf'
alias stopmongo='killall mongod'
alias findmongo='lsof -iTCP -sTCP:LISTEN | grep mongod'

# Control spotlight
alias togglespotlight='sudo mdutil -a -i off'

# Get my current IP addresses
alias myip="dig TXT +short o-o.myaddr.l.google.com @ns1.google.com"
# Get ip of local network
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"
# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"
# View HTTP traffic
alias sniff="sudo grep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd="hexdump -C"

# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# JavaScriptCore REPL
jscbin="/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc";
[ -e "${jscbin}" ] && alias jsc="${jscbin}";
unset jscbin;

# Recursively delete node_modules and other build folders
alias cleanup="find . \( -name "node_modules" -o -name ".next" -o -name "dist" -o -name "out" \) -type d -prune -exec rm -rf {} +"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# Show/hide hidden files in Finder
alias showfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidefiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
# URL-encode strings
alias urlencode='python3 -c "import sys, urllib.parse as ul; print(ul.quote_plus(sys.argv[1]))"'

# Flush DNS cache
alias flushdns='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'

# PlistBuddy alias, because sometimes `defaults` just doesn’t cut it
alias plistbuddy="/usr/libexec/PlistBuddy"

# Airport CLI alias
alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
	alias "$method"="lwp-request -m '$method'"
done

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

alias claude='$HOME/.claude/local/claude'
