require "sang.core.launch"
require "sang.core.options"
require "sang.core.keymaps"
require "sang.core.autocmds"

-- spec "sang.plugins.harpoon"
-- spec "sang.plugins.illuminate"
-- spec "sang.plugins.navic"
-- spec "sang.plugins.rename"
-- spec "sang.plugins.schemastore"
-- spec "sang.plugins.ufo"
-- spec "sang.plugins.whichkey"
-- spec "sang.plugins.ai"
spec "sang.plugins.alpha"
spec "sang.plugins.autopairs"
spec "sang.plugins.autosave"
spec "sang.plugins.autotags"
-- spec "sang.plugins.avante"
spec "sang.plugins.bqf"
spec "sang.plugins.bufferline"
-- spec "sang.plugins.claudecode"
spec "sang.plugins.cmp"
spec "sang.plugins.colorizer"
spec "sang.plugins.colorscheme"
spec "sang.plugins.comment"
spec "sang.plugins.devicons"
spec "sang.plugins.formatters"
spec "sang.plugins.gitsigns"
spec "sang.plugins.hop"
spec "sang.plugins.indentline"
spec "sang.plugins.linters"
spec "sang.plugins.lspconfig"
spec "sang.plugins.lspsaga"
spec "sang.plugins.lualine"
spec "sang.plugins.mason"
-- spec "sang.plugins.mcp"
spec "sang.plugins.mini"
spec "sang.plugins.nvimtree"
spec "sang.plugins.sessions"
spec "sang.plugins.snacks"
spec "sang.plugins.spider"
spec "sang.plugins.splitjoin"
spec "sang.plugins.tabnine"
spec "sang.plugins.telescope"
spec "sang.plugins.stream_writer"
spec "sang.plugins.todo"
spec "sang.plugins.toggleterm"
spec "sang.plugins.treesitter"

require "sang.core.lazy"
