#!/bin/bash
# post-checkout

# Git post checkout hook.
# ------------------------------------------------------
# Reminds you to update Node dependencies, if necessary

PREVIOUS_HEAD=$1
NEW_HEAD=$2
BRANCH_SWITCH=$3

NPM_LOCK=./package-lock.json
YARN_LOCK=./yarn.lock

echo '> Start running the post-checkout hook...'

if [[ $BRANCH_SWITCH == "1" && $PREVIOUS_HEAD != $NEW_HEAD && $PREVIOUS_HEAD != "0000000000000000000000000000000000000000" ]]; then
    # Start from the repository root.
    cd ./$(git rev-parse --show-cdup)
    echo '> Fetched and pruned branches...'
    git fetch origin --prune

    # Check if requirements have been updated - npm/yarn
    REQUIREMENTS=`git diff $PREVIOUS_HEAD $NEW_HEAD --name-status | grep "package.json"`

    if [ $? -eq 0 ]; then
        echo '> The origin has updated. Pulling them...'
        git pull origin

        if [ -f "$YARN_LOCK" ]; then
          echo '> Detected yarn.lock, use yarn install...'
          yarn install
        fi

        if [ -f "$NPM_LOCK" ]; then
          echo '> Detected npm lock, use npm install...'
          npm install
        fi
    fi
fi
