# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$battery\
$line_break\
$character"""

scan_timeout = 300
command_timeout = 1400

[directory]
style = "bold blue"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[](bold green)"

[git_branch]
symbol = " "
style = "bright-yellow"
format = "[$symbol$branch]($style) "

[git_state]
style = "bright-yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_status]
style = "bright-black"
conflicted = "[ ${count}](red) "
untracked = "[ ${count}](yellow) "
modified = "[ ${count}](blue) "
staged = "[ ${count}](green) "
renamed = "[ ${count}](yellow) "
deleted = "[ ${count}](gray) "
ahead = "[${ahead_count}]($style)"
behind = "[${behind_count}]($style)"
diverged = "[${ahead_count} ${behind_count}]($style) "
stashed = "[ ${count}](bright-black) "
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
style = "bright-black"
format = "[$duration]($style) "

[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "

[[battery.display]]
threshold = 30
style = "red"
