# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

scan_timeout = 300
command_timeout = 1400

[directory]
style = "blue"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
style = "cyan"
conflicted = " (red)"
ahead = "[ ${count}](blue) "
behind = "[ ${count}](red) "
untracked = "[ ${count}](yellow) "
stashed = "[ ${count}](purple) "
modified = "[ ${count}](blue) "
staged = "[ ${count}](green) "
renamed = "[ ${count}](yellow) "
deleted = "[ ${count}](gray) "
format = "[[(* $conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
