# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
# add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

scan_timeout = 300
command_timeout = 1400

[directory]
style = "blue"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[](bold green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
style = "bright-black"
conflicted = "[ ${count}](red) "
untracked = "[ ${count}](yellow) "
modified = "[ ${count}](blue) "
staged = "[ ${count}](green) "
renamed = "[ ${count}](yellow) "
deleted = "[ ${count}](gray) "
diverged = "[${ahead_count} ${behind_count}](bright-black) "
stashed = "[ ${count}](bright-black) "
format = "[[(* $conflicted$untracked$modified$staged$renamed$deleted)](218) ($diverged$stashed)]($style) "

[cmd_duration]
style = "bright-black"
format = "[$duration]($style) "

[python]
style = "bright-black"
format = "[$virtualenv]($style) "
