quitOnTopLevelReturn: false
promptToReturnFromSubprocess: false
os:
  edit: "lvim {{filename}}"
  editAtLine: "lvim +{{line}} {{filename}}"
  editAtLineAndWait: "lvim +{{line}} {{filename}}"
git:
  commitPrefixes:
    lokalise-main:
      pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: "$1 "
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  nerdFontsVersion: "3"
  sidePanelWidth: 0.3
  mainPanelSplitMode: "vertical"
  theme:
    inactiveBorderColor:
      - "#4A5568"
    selectedLineBgColor:
      - "#2D3748"
    cherryPickedCommitBgColor:
      - "#1f2335"
    cherryPickedCommitFgColor:
      - "#0BC5EA"
      - bold
  authorColors:
    "Sang Dang": magenta
    "*": blue
  branchColors:
    feature: white
    bugfix: white
    develop: blue
    master: magenta
    main: magenta
