lastupdatecheck: 0
recentrepos:
- /Users/sangdang/dotfiles
- /Users/sangdang/Lokalise/styled
- /Users/sangdang/Projects/lakihelppi/dashboard
- /Users/sangdang/Lokalise/lokalise-main
- /Users/sangdang/Lokalise/louis
- /Users/sangdang/Lokalise/npm-package-template
- /Users/sangdang/Lokalise/web-starter-template
- /Users/sangdang/Projects/issueradar
- /Users/sangdang/Projects/lakihelppi/foundations
- /Users/sangdang/Projects/rassue
- /Users/sangdang/Projects/scroll-and-float
- /Users/sangdang/Projects/tree-sitter-mdx
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: true
