lastupdatecheck: 0
recentrepos:
- /Users/sang/dotfiles
- /Users/sang/Projects/lakihelppi/lakihelppi
- /Users/sang/Projects/enviro
- /Users/sang/Projects/lakihelppi/laki-test
- /Users/sang/Projects/lakihelppi/laki-in-shtf
- /Users/sang/Projects/sieutoc/voi
- /Users/sang/Projects/sieutoc/platform
- /Users/sang/Projects/sieutoc/blocklistrescue
- /Users/sang/Projects/sieutoc/sieutoc
- /Users/sang/Projects/sieutoc/taijutsu
- /Users/sang/Projects/sieutoc/syva
- /Users/sang/Projects/sieutoc/ui
- /Users/sang/Projects/sieutoc/miselist
- /Users/sang/Projects/sieutoc/genjutsu
- /Users/sang/Projects/sieutoc/pika
- /Users/sang/Projects/worklog
- /Users/sang/Projects/sieutoc/github
- /Users/sang/Projects/sieutoc/reset-platform
- /Users/sang/Projects/sieutoc/backup-cron
- /Users/sang/Projects/sieutoc/mintlify-docs
- /Users/sang/Projects/sieutoc/ninjutsu
- /Users/sang/Projects/sieutoc/easypanel
- /Users/sang/Projects/sieutoc/customers/bemp
- /Users/sang/Projects/langchain-llm-learning
- /Users/sang/Projects/lakihelppi/spider
- /Users/sang/Projects/lakihelppi/backup-cron
- /Users/sang/Projects/sieutoc/cake-editor
- /Users/sang/Projects/booksao/booksao
- /Users/sang/Projects/issueradar/dashboard
- /Users/sang/Projects/prep-master
- /Users/sang/Projects/prep-master2
- /Users/sang/Projects/sieutoc/themes
- /Users/sang/Projects/kien
- /Users/sang/Projects/lakihelppi/leadoo
startuppopupversion: 5
lastversion: 0.41.0
customcommandshistory:
- qa
hidecommandlog: true
ignorewhitespaceindiffview: false
diffcontextsize: 3
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
