lastupdatecheck: 0
recentrepos:
- /Users/sangdang/dotfiles
- /Users/sangdang/Lokalise/lokalise-main
- /Users/sangdang/Lokalise/louis
- /Users/sangdang/Projects/lakihelppi/foundations
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: true
