lastupdatecheck: 0
recentrepos:
- /Users/sang/Projects/sieutoc/taijutsu
- /Users/sang/Projects/lakihelppi/lakihelppi
- /Users/sang/Projects/sieutoc/platform
- /Users/sang/Projects/sieutoc/customers/bemp
- /Users/sang/Projects/lakihelppi/backup-cron
- /Users/sang/dotfiles
startuppopupversion: 5
customcommandshistory:
- qa
hidecommandlog: true
ignorewhitespaceindiffview: false
