lastupdatecheck: 0
recentrepos:
- /Users/sangdang/Lokalise/lokalise-main
- /Users/sangdang/Lokalise/louis
- /Users/sangdang/Projects/lakihelppi/foundations
- /Users/sangdang/Projects/lakihelppi/foundations/apps/dashboard
- /Users/sangdang/dotfiles
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: true
